name: Test CLI Installation
on: [push, pull_request]

jobs:
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install package
        run: pip install -e .
        
      - name: Test CLI works
        run: sherlock --help 